application: amasoeany
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /widget.html
  static_files: static/widget.html
  upload: static/widget.html

- url: /(.*\.(gif|png|jpg|js|css|less|ico|woff|tff|svg|eot|tmpl))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|js|css|less|ico|woff|tff|svg|eot|tmpl))

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
